# Generated by Django 3.1.2 on 2021-04-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
