# Generated by Django 3.1.2 on 2021-04-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='code',
            field=models.CharField(max_length=3),
        ),
    ]
