# Generated by Django 3.1.2 on 2021-05-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_menu_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(default='meal', max_length=4),
        ),
    ]
